name: 刷步数

on:
  schedule:
    - cron: '58 1,4,7,10,12,14,23 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout codes
        # 使用 actions/checkout v4.2.2 的 SHA
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 
        with:
          token: ${{ secrets.PAT }}

      - name: Update system and install zsh
        run: |
          sudo -E apt-get -qq update
          sudo -E apt-get install zsh -y
          
      - name: 初始化Python
        # 使用 actions/setup-python v5.3.0 的最新 SHA
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491f071c369 
        with:
          python-version: "3.10"

          
      - name: 开始
        env:
            CONFIG: ${{ secrets.CONFIG }}
            AES_KEY: ${{ secrets.AES_KEY }}
        run: |
          pip3 install requests pytz pycryptodome
          python3 main.py

      - name: persist tokens
        run: |
          git config user.name github-actions
          git config user.email github-actions@users.noreply.github.com
          git add .
          git commit -m "persist tokens trigger by ${{ github.event_name }}"
          git push origin master
